// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxhfuxmuzsditfgsrbdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4aGZ1eG11enNkaXRmZ3NyYmRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODA5NjIsImV4cCI6MjA3MjU1Njk2Mn0.a5lVTExe5_6F4DbxA_7QIonAgvA_Ds0pAz_dnbLojB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});