// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcibbanlxcpycqtqrfmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjaWJiYW5seGNweWNxdHFyZm13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTU5NDUsImV4cCI6MjA3MDQzMTk0NX0.YVAPKkOc7FHgMUy3w5v5fnGeWS4xz8Ttz3gBMzhto-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});